"""Trusted executor: verify, render via a fixed template, upsert one comment.

Runs in the post job (the only job holding `pull-requests: write`). Trusts
nothing from the review job: re-runs the verifier here, re-checks the PR head
SHA still equals the reviewed SHA (TOCTOU guard), then renders the artifact
through a fixed template and upserts a single sticky comment identified by a
hidden HTML marker.

Any verifier rejection or SHA mismatch: nothing is posted, exit non-zero.

Comment ownership is marker AND author, and the author half is resolved at
runtime from the write token itself (resolve_bot_login) rather than configured:
a configured login can drift from the token actually posting, and this value
decides which prior comments the executor may edit. Unresolvable identity is
also fail-closed.

Environment: GITHUB_TOKEN, GITHUB_REPOSITORY, PR_NUMBER, HEAD_SHA, BASE_SHA,
RUN_URL, BEDROCK_INFERENCE_PROFILE (attribution stamp only).
Arguments: --artifact-dir (review.json + context files), --policy, --prompt, and
optionally --marker/--title to identify which generator's comment this is.

One executor, several generators. `--marker` exists because the comment identity
is per-GENERATOR while this code is shared: two reviewers posting under one marker
would upsert the SAME comment and overwrite each other's review. Copying this file
per generator was the alternative and is worse -- it is the verifier boundary, so a
fork means the trusted re-verification drifts per generator.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
from typing import cast

from github_api import api_json, fail, paginate
from verify import Rejection, verify

# The incumbent's marker and heading. Defaults, so a caller passing neither posts
# exactly what it always did; a second generator overrides both.
MARKER = "<!-- ai-pr-review-sticky-comment -->"
TITLE = "🤖 AI Code Review"

# Presentation only; severity *order* comes from policy.json's enum (most
# severe first), the single home of the severity vocabulary.
SEVERITY_LABEL = {
    "critical": "🔴 Critical",
    "high": "🟠 High",
    "medium": "🟡 Medium",
    "low": "🔵 Low",
}


def render(
    artifact: dict,
    metadata: dict,
    severity_order: dict[str, int],
    marker: str = MARKER,
    title: str = TITLE,
) -> str:
    """Fixed template. Model text is inserted verbatim only after the verifier
    has proven it inside the safe grammar; everything structural is ours.

    `marker` and `title` are the only per-generator parts, and both are ours
    rather than the model's -- they are never taken from the artifact.
    """
    lines = [
        marker,
        f"## {title}",
        "",
        "> [!NOTE]",
        "> This review was generated by an AI model. It is **not a human review**, "
        "may be wrong, and counts toward **no approval**. Treat it as a hint list.",
        "",
        "### Summary",
        "",
        artifact["summary"],
        "",
    ]

    findings = sorted(artifact["findings"], key=lambda f: severity_order[f["severity"]])
    if findings:
        lines += ["### Findings", ""]
        for finding in findings:
            lines += [
                f"#### {SEVERITY_LABEL.get(finding['severity'], finding['severity'])} — {finding['title']}",
                "",
                f"`{finding['path']}` line {finding['line']}",
                "",
                finding["body"],
                "",
            ]
    else:
        lines += ["### Findings", "", "No confirmed defects found.", ""]

    if artifact["residual_risk"]:
        lines += ["### Residual risk", "", artifact["residual_risk"], ""]

    lines += [
        "---",
        "<sub>model: `{model}` · prompt: `{prompt}` · policy: `{policy}` · "
        "reviewed SHA: `{sha}` · [run]({run_url})</sub>".format(**metadata),
    ]
    return "\n".join(lines)


VIEWER_LOGIN_QUERY = "query { viewer { login } }"


def resolve_bot_login() -> str:
    """The login the write token authenticates as, asked of the token itself.

    This decides which prior comments are OURS to edit or supersede: anyone can
    paste the marker into their own comment, so ownership is marker AND author,
    and the author half must come from the credential in hand -- a configured
    value can silently disagree with the token actually posting (the exact drift
    a consumer swapping GITHUB_TOKEN for an app token would introduce).

    GraphQL rather than REST GET /user because it is the one identity call every
    token type answers: /user is 403 "Resource not accessible by integration"
    for app installation tokens, which is what Actions' GITHUB_TOKEN is. For a
    bot, viewer.login comes back WITH the "[bot]" suffix (github-actions[bot],
    <app-slug>[bot]) -- byte-identical to the user.login on comments the token
    creates, so no mapping sits between resolution and the ownership check.

    Fail-closed: anything but a non-empty login exits without posting. Guessing
    here means the executor may edit comments it does not own.
    """
    response = api_json("/graphql", method="POST", payload={"query": VIEWER_LOGIN_QUERY})
    login = None
    if isinstance(response, dict):
        login = (((response.get("data") or {}).get("viewer")) or {}).get("login")
    if not isinstance(login, str) or not login:
        fail(f"could not resolve the token's own login, nothing posted (response: {json.dumps(response)[:300]})")
    return login


def upsert_comment(repo: str, pr_number: int, body: str, marker: str = MARKER, *, bot_login: str) -> None:
    """Update this generator's own sticky comment, or create it.

    Matched on `marker` AND author. The marker must be the SAME one render() wrote,
    or a reviewer would search for a comment it never posts and create a new one
    every run -- so callers pass one value to both. `bot_login` is keyword-only
    and has no default because it is the security half of the match: the one
    valid source is resolve_bot_login(), and a hardcoded fallback would be the
    coupling this parameter replaced.
    """
    existing_id = next(
        (
            comment["id"]
            for page in paginate(f"/repos/{repo}/issues/{pr_number}/comments?")
            for comment in page
            if marker in (comment.get("body") or "") and (comment.get("user") or {}).get("login") == bot_login
        ),
        None,
    )

    if existing_id is not None:
        api_json(f"/repos/{repo}/issues/comments/{existing_id}", method="PATCH", payload={"body": body})
        print(f"updated existing comment {existing_id}")
    else:
        api_json(f"/repos/{repo}/issues/{pr_number}/comments", method="POST", payload={"body": body})
        print("created new comment")


# Kept inside the model-field safe grammar (no blockquote/heading — those are
# disallowed even for us where a test can hold us to it) so the one static
# body post.py writes is provably within the same envelope it enforces.
STALE_NOTICE = (
    "**AI review withdrawn.** The PR's head or base changed while the review "
    "was being posted, so it described a different diff. A new review will be "
    "posted by the run for the current revision."
)


def check_pr_unmoved(repo: str, pr_number: int, reviewed_head: str, reviewed_base: str) -> str | None:
    """Return None if the PR still points at the reviewed head AND base,
    else a human-readable description of what moved. The base matters too:
    a retarget (head unchanged, base edited) changes the diff the review
    claims to describe just as surely as a push does."""
    pr = cast("dict", api_json(f"/repos/{repo}/pulls/{pr_number}"))
    head, base = pr["head"]["sha"], pr["base"]["sha"]
    if head != reviewed_head:
        return f"head moved since review ({head} != {reviewed_head})"
    if base != reviewed_base:
        return f"base changed since review ({base} != {reviewed_base})"
    return None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact-dir", required=True, type=Path)
    parser.add_argument("--policy", required=True, type=Path)
    parser.add_argument("--prompt", required=True, type=Path)
    # Default to the incumbent's identity so its call site is unchanged.
    parser.add_argument("--marker", default=MARKER, help="Hidden HTML marker identifying this generator's comment.")
    parser.add_argument("--title", default=TITLE, help="Comment heading naming the generator.")
    args = parser.parse_args()

    repo = os.environ["GITHUB_REPOSITORY"]
    pr_number = int(os.environ["PR_NUMBER"])
    reviewed_sha = os.environ["HEAD_SHA"]
    reviewed_base = os.environ["BASE_SHA"]

    artifact = json.loads((args.artifact_dir / "review.json").read_text())
    diff_text = (args.artifact_dir / "diff.patch").read_text()
    changed_files = json.loads((args.artifact_dir / "changed_files.json").read_text())
    policy_text = args.policy.read_text()
    policy = json.loads(policy_text)

    # Verification happens HERE, where the write token lives. Job 2's claims
    # about having verified anything are not trusted.
    try:
        verify(artifact, diff_text, changed_files, policy)
    except Rejection as exc:
        fail(f"artifact rejected, nothing posted: {exc}")

    # TOCTOU guard, first half: the PR must still point at the reviewed head
    # and base before we render anything.
    if moved := check_pr_unmoved(repo, pr_number, reviewed_sha, reviewed_base):
        fail(f"{moved}; nothing posted")

    # Resolved before the first write and reused for the withdrawal: the two
    # upserts must agree on identity, or a stale notice could land in a new
    # comment while the outdated review stays up.
    bot_login = resolve_bot_login()

    metadata = {
        "model": os.environ["BEDROCK_INFERENCE_PROFILE"],
        "prompt": hashlib.sha256(args.prompt.read_bytes()).hexdigest()[:12],
        "policy": hashlib.sha256(policy_text.encode()).hexdigest()[:12],
        "sha": reviewed_sha,
        "run_url": os.environ["RUN_URL"],
    }
    severities = policy["artifact_schema"]["findings"]["item_fields"]["severity"]["values"]
    severity_order = {name: rank for rank, name in enumerate(severities)}
    body = render(artifact, metadata, severity_order, args.marker, args.title)
    upsert_comment(repo, pr_number, body, args.marker, bot_login=bot_login)

    # TOCTOU guard, second half: the pre-check and the write are not atomic —
    # a push (or base retarget) landing between them leaves a review describing
    # the OLD diff attached to the new one, with no run to correct it if the
    # attacker cancels the new revision's workflow. Recheck after the write;
    # if the PR moved, overwrite our comment with a stale notice and fail.
    if moved := check_pr_unmoved(repo, pr_number, reviewed_sha, reviewed_base):
        upsert_comment(repo, pr_number, f"{args.marker}\n{STALE_NOTICE}", args.marker, bot_login=bot_login)
        fail(f"{moved} while posting; review withdrawn")


if __name__ == "__main__":
    main()
